BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "superbird-mic-debug"
BBFILE_PATTERN_superbird-mic-debug := "^${LAYERDIR}/"
BBFILE_PRIORITY_superbird-mic-debug = "20"

LAYERVERSION_superbird-mic-debug = "1"
LAYERSERIES_COMPAT_superbird-mic-debug = "scarthgap wrynose"
LAYERDEPENDS_superbird-mic-debug = "core superbird meson chromium-browser-layer"
