require conf/distro/superbird.conf

DISTRO = "superbird-mic-debug"
DISTRO_NAME = "Superbird Mic Debug"
DISTRO_VERSION = "0.1.0"

SUPERBIRD_HOSTNAME = "mic-debug"
SUPERBIRD_MDNS_SERVICE_NAME = "Mic Debug"
SUPERBIRD_USB_GADGET_NAME = "mic-debug"
SUPERBIRD_USB_GADGET_MANUFACTURER = "bridgething"
SUPERBIRD_USB_GADGET_PRODUCT = "Superbird Mic Debug"

CHROMIUM_KIOSK_URL = "http://127.0.0.1:8099/"
