require conf/distro/superbird.conf

DISTRO = "superbird-kiosk"
DISTRO_NAME = "Superbird Kiosk Example"
DISTRO_VERSION = "0.1.0"

# identity / brand. override per your product.
SUPERBIRD_HOSTNAME = "superbird-kiosk"
SUPERBIRD_MDNS_SERVICE_NAME = "Superbird Kiosk"
SUPERBIRD_USB_GADGET_NAME = "superbird-kiosk"
SUPERBIRD_USB_GADGET_MANUFACTURER = "superbird-kiosk"
SUPERBIRD_USB_GADGET_PRODUCT = "Superbird Kiosk"

# baked into chromium-kiosk at do_install. point at your webapp.
CHROMIUM_KIOSK_URL = "file:///usr/share/superbird-kiosk-default/index.html"
