DEFAULT bridgething
PROMPT 0
TIMEOUT 0

LABEL bridgething
    KERNEL Image.gz
    FDT meson-g12a-superbird.dtb
    APPEND root=PARTLABEL=root_${slot} ro rootwait console=ttyAML0,115200n8 earlycon=meson,0xff803000 no_console_suspend ramoops.pstore_en=1 ramoops.record_size=0x8000 ramoops.console_size=0x4000 superbird.max_cpufreq_khz=${charger_cap_khz} superbird.slot=${slot}
