BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "superbird-kiosk-example"
BBFILE_PATTERN_superbird-kiosk-example := "^${LAYERDIR}/"
BBFILE_PRIORITY_superbird-kiosk-example = "8"

LAYERVERSION_superbird-kiosk-example = "1"
LAYERSERIES_COMPAT_superbird-kiosk-example = "wrynose"
LAYERDEPENDS_superbird-kiosk-example = "core superbird meson chromium-browser-layer"
