BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "bridgething"
BBFILE_PATTERN_bridgething = "^${LAYERDIR}/"
BBFILE_PRIORITY_bridgething = "20"

LAYERSERIES_COMPAT_bridgething = "scarthgap wrynose"

LAYERDEPENDS_bridgething = "core superbird"
